server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
 
spring:
 cloud:
  #Importan: Ribbon is still the default client-side load balancer, must disable it
  loadbalancer.ribbon.enabled: false
  gateway:
   discovery.locator:
    enabled: true
    lowerCaseServiceId: true


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        