package jda.modules.restfstool;

import java.util.Set;

import org.jda.example.restfstool.rfsgen.BackendMain;
import org.reflections.Reflections;

import jda.modules.restfstool.frontend.utils.DomainTypeRegistry;

/**
 * @overview 
 *  Executes a back-end that was generated by {@link RFSGen}.
 *  
 * @author Duc Minh Le (ducmle)
 *
 * @version 
 */
public class BackEndSoftware {
  
  /**
   * @effects 
   *  executes SpringBoot application from the specified back-end components
   */
  public void run(Class<?>[] model, Class<?>[] auxModel,
      String backendTargetPackage
//    ,String backendSrcPath
      ) {
    // initialisation
    init(model, auxModel);
    
    // load classes from the backEndPath
    Reflections refl = new Reflections(backendTargetPackage); 
    Set<? extends Class> comps = refl.getSubTypesOf(Class.class);
    
    // run SpringBoot
    new BackendMain(model).run(comps);
  }

  /**
   * Similar to {@link RFSGen#init}
   * @effects 
   *  
   */
  private void init(Class<?>[] model, Class<?>[] auxModel) {
    DomainTypeRegistry regist = DomainTypeRegistry.getInstance();
    regist.addDomainTypes(model);
    for (Class<?> other : auxModel) {
      regist.addDomainType(other);
    }
  }
}
